"use client";

import { RankingTable } from "./RankingTable";

const honorableMentionsCourses = [
  {
    rank: 11,
    name: "Kongsvingers Golfklubb",
    region: "Innlandet",
    rating: 4.6,
    reviewCount: 211,
    score: 4.58,
    courseSlug: "kongsvinger-golfklubb",
    regionSlug: "innlandet",
  },
  {
    rank: 12,
    name: "Fana Golfklubb",
    region: "Vestland",
    rating: 4.6,
    reviewCount: 203,
    score: 4.58,
    courseSlug: "fana-golfklubb",
    regionSlug: "vestland",
  },
  {
    rank: 13,
    name: "Moss & Rygge Golfklubb",
    region: "Østfold",
    rating: 4.6,
    reviewCount: 189,
    score: 4.57,
    courseSlug: "moss-rygge-golfklubb",
    regionSlug: "ostfold",
  },
  {
    rank: 14,
    name: "Onsøy Golfklubb",
    region: "Østfold",
    rating: 4.6,
    reviewCount: 187,
    score: 4.57,
    courseSlug: "onsoy-golfklubb",
    regionSlug: "ostfold",
  },
  {
    rank: 15,
    name: "Kjekstad Golfklubb",
    region: "Buskerud",
    rating: 4.6,
    reviewCount: 182,
    score: 4.57,
    courseSlug: "kjekstad-golfklubb",
    regionSlug: "buskerud",
  },
  {
    rank: 16,
    name: "Tyrifjord Golfklubb",
    region: "Buskerud",
    rating: 4.6,
    reviewCount: 180,
    score: 4.57,
    courseSlug: "tyrifjord-golfklubb",
    regionSlug: "buskerud",
  },
  {
    rank: 17,
    name: "Bleik Golfstrømbane",
    region: "Nordland",
    rating: 4.7,
    reviewCount: 38,
    score: 4.57,
    courseSlug: "bleik-golfstrombane",
    regionSlug: "nordland",
  },
  {
    rank: 18,
    name: "Oslo Golfklubb",
    region: "Oslo",
    rating: 4.6,
    reviewCount: 158,
    score: 4.57,
    courseSlug: "oslo-golfklubb",
    regionSlug: "oslo",
  },
  {
    rank: 19,
    name: "Nordvegen Golfklubb",
    region: "Rogaland",
    rating: 4.6,
    reviewCount: 149,
    score: 4.57,
    courseSlug: "nordvegen-golfklubb",
    regionSlug: "rogaland",
  },
  {
    rank: 20,
    name: "Meland Golfklubb",
    region: "Vestland",
    rating: 4.6,
    reviewCount: 148,
    score: 4.57,
    courseSlug: "meland-golfklubb",
    regionSlug: "vestland",
  },
];

export function HonorableMentionsTable() {
  return <RankingTable courses={honorableMentionsCourses} />;
}
