"use client";

import { RankingTable } from "./RankingTable";

// Top 10 Norwegian Golf Courses 2026 data
// change: positive = moved up, negative = moved down, 0 = same, "new" = new entry
const top10Courses = [
  {
    rank: 1,
    name: "Stiklestad Golfklubb",
    region: "Trøndelag",
    rating: 4.9,
    reviewCount: 118,
    score: 4.81,
    courseSlug: "stiklestad-golfklubb",
    regionSlug: "trondelag",
    change: 0,
  },
  {
    rank: 2,
    name: "Trondheim Golfklubb",
    region: "Trøndelag",
    rating: 4.9,
    reviewCount: 36,
    score: 4.69,
    courseSlug: "trondheim-golfklubb",
    regionSlug: "trondelag",
    change: 0,
  },
  {
    rank: 3,
    name: "Bjaavann Golfklubb",
    region: "Agder",
    rating: 4.7,
    reviewCount: 108,
    score: 4.64,
    courseSlug: "bjaavann-golfklubb",
    regionSlug: "agder",
    change: 0,
  },
  {
    rank: 4,
    name: "Oustøen Country Club",
    region: "Akershus",
    rating: 4.7,
    reviewCount: 90,
    score: 4.63,
    courseSlug: "oustoen-country-club",
    regionSlug: "akershus",
    change: 0,
  },
  {
    rank: 5,
    name: "Molde Golfklubb",
    region: "Møre og Romsdal",
    rating: 4.7,
    reviewCount: 89,
    score: 4.63,
    courseSlug: "molde-golfklubb",
    regionSlug: "more-og-romsdal",
    change: 0,
  },
  {
    rank: 6,
    name: "Valdres Golfklubb",
    region: "Innlandet",
    rating: 4.7,
    reviewCount: 80,
    score: 4.62,
    courseSlug: "valdres-golfklubb",
    regionSlug: "innlandet",
    change: 0,
  },
  {
    rank: 7,
    name: "Bodø Golfpark",
    region: "Nordland",
    rating: 4.7,
    reviewCount: 72,
    score: 4.62,
    courseSlug: "bodo-golfpark",
    regionSlug: "nordland",
    change: 0,
  },
  {
    rank: 8,
    name: "Krokhol Golfklubb",
    region: "Akershus",
    rating: 4.6,
    reviewCount: 223,
    score: 4.58,
    courseSlug: "krokhol-golfklubb",
    regionSlug: "akershus",
    change: 1,
  },
  {
    rank: 9,
    name: "Kongsvingers Golfklubb",
    region: "Innlandet",
    rating: 4.6,
    reviewCount: 211,
    score: 4.58,
    courseSlug: "kongsvinger-golfklubb",
    regionSlug: "innlandet",
    change: "new" as const,
  },
  {
    rank: 10,
    name: "Lofoten Links",
    region: "Nordland",
    rating: 4.6,
    reviewCount: 281,
    score: 4.58,
    courseSlug: "lofoten-links",
    regionSlug: "nordland",
    change: -2,
  },
];

export function Top10RankingTable() {
  return <RankingTable courses={top10Courses} />;
}
